version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - 3000:3000
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - 3001:3000
